### ISSUE TITLE
Uncaught ReferenceError at aframe-tangram-component

### ISSUE THREAD

**Issue by turtlebond** [mattrei/aframe-tangram-component#2]
Hi.
I was running the example @ https://mattrei.github.io/aframe-tangram-component/examples/basic/
I encounter error as following: 
aframe-tangram-component.min.js:1 Uncaught ReferenceError: require is not defined
    at aframe-tangram-component.min.js:1
    at aframe-tangram-component.min.js:1
    at aframe-tangram-component.min.js:1

How can I bypass this error?

**Comment by mattrei** [comment]
fixed in #416b5219

**Comment by mattrei** [comment]
fixed in @416b5210
